name: Run Tests CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: museumprojecttesting
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          sudo apt-get install -y mysql-client
          until mysql -h 127.0.0.1 -u root -proot -e "SELECT 1;" &> /dev/null; do
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Run tests
        run: mvn test